test:
  image: python:3.6
  script:
    - apt-get update -q -y
    - apt-get install python3-setuptools -q -y
    - apt-get install python3-pip -q -y
    - apt-get install build-essential checkinstall -q -y
    - apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev -q -y
    - pip3 install -r requirements.txt
    - python tests.py -m unittest discover -s project_directory -p "*_test.py"~